### ISSUE TITLE
Paper "Information preservation pooling for speaker embedding"

### ISSUE THREAD

**Issue by gancx** [msh9184/contrastive-equilibrium-learning#1]
Thanks for your interesting work. I wonder for the paper I mentioned, in the GIM design, the input size should be as same as the output size of the frame-level feature. But in your diagram, they are T-14 and T-12, respectively. Also, can you share your implementation of the work? Thanks.

**Comment by msh9184** [comment]
Hi @gancx, thank you for your interest.
Specifically, could you please explain in more detail what GIM design, dimension T-12 and T-14 you are referring to?
And also, you can find the implementation and released checkpoints used in this paper at this repo.

**Comment by gancx** [comment]
> Hi @gancx, thank you for your interest. Specifically, could you please explain in more detail what GIM design, dimension T-12 and T-14 you are referring to? And also, you can find the implementation and released checkpoints used in this paper at this repo.

I mean in Table 1, the input size (T-12 * 1536) for the global discriminator seems different from the output size of frame-level features (T-14 * 1536) in terms of temporal level. Thanks.

**Comment by gancx** [comment]
> Hi @gancx, thank you for your interest. Specifically, could you please explain in more detail what GIM design, dimension T-12 and T-14 you are referring to? And also, you can find the implementation and released checkpoints used in this paper at this repo.

Sorry, I do NOT find any implementation about this paper "Information preservation pooling for speaker embedding".

**Comment by msh9184** [comment]
I got it. Can you send e-mail the first author? (mhhan@hi.snu.ac.kr)
Maybe he will answer.

**Comment by gancx** [comment]
Sure, thanks for your help.

**Comment by BritPop** [comment]
hello @gancx  I m the writer of the paper

input size T-12 means that (T-14) frames of local-level features and  (1) for weighted mean embedding and (1) for weighted standard deviation embedding 
T-12 = (T-14)+1 +1

Therefore, the GIM network gets input from (T-14) local-level features  and the global-level feature as input

**Comment by gancx** [comment]
> hello @gancx I m the writer of the paper
> 
> input size T-12 means that (T-14) frame size and (1) for weighted mean embedding and (1) for weighted standard deviation embedding T-12 = (T-14)+1 +1
> 
> Therefore, the GIM network gets input from (T-14) local-level features and the global-level feature as input

Oh, I see. "-" is the minus symbol. Appreciate your answer. I wonder if you will share your implementation?

**Comment by BritPop** [comment]
> > hello @gancx I m the writer of the paper
> > input size T-12 means that (T-14) frame size and (1) for weighted mean embedding and (1) for weighted standard deviation embedding T-12 = (T-14)+1 +1
> > Therefore, the GIM network gets input from (T-14) local-level features and the global-level feature as input
> 
> Oh, I see. "-" is the minus symbol. Appreciate your answer. I wonder if you will share your implementation?

Because It's an experiment that I ran a long time ago,  i m sorry that I can't find it because the computing server I use changed

**Comment by gancx** [comment]
> > > hello @gancx I m the writer of the paper
> > > input size T-12 means that (T-14) frame size and (1) for weighted mean embedding and (1) for weighted standard deviation embedding T-12 = (T-14)+1 +1
> > > Therefore, the GIM network gets input from (T-14) local-level features and the global-level feature as input
> > 
> > 
> > Oh, I see. "-" is the minus symbol. Appreciate your answer. I wonder if you will share your implementation?
> 
> Because It's an experiment that I ran a long time ago, i m sorry that I can't find it because the computing server I use changed

Ok, appreciate your help. Thank you.
